// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AdventureWorksContext))]
    partial class AdventureWorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Color");

                    b.Property<int>("DaysToManufacture")
                        .HasColumnType("int")
                        .HasColumnName("DaysToManufacture");

                    b.Property<DateTime?>("DiscontinuedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DiscontinuedDate");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("money")
                        .HasColumnName("ListPrice");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("ProductNumber");

                    b.Property<int?>("ProductSubcategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSubcategoryID");

                    b.Property<short>("ReorderPoint")
                        .HasColumnType("smallint")
                        .HasColumnName("ReorderPoint");

                    b.Property<short>("SafetyStockLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("SafetyStockLevel");

                    b.Property<DateTime?>("SellEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SellEndDate");

                    b.Property<DateTime>("SellStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SellStartDate");

                    b.Property<string>("Size")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Size");

                    b.Property<decimal>("StandardCost")
                        .HasColumnType("money")
                        .HasColumnName("StandardCost");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("Weight");

                    b.HasKey("ProductId");

                    b.ToTable("Product", "Production");
                });

            modelBuilder.Entity("Backend.Models.ProductNote", b =>
                {
                    b.Property<int>("ProductNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductNoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.HasKey("ProductNoteId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductNotes");
                });

            modelBuilder.Entity("Backend.Models.ProductNote", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("ProductNotes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("ProductNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
